### ISSUE TITLE
About success rate

### ISSUE THREAD

**Issue by ding15963** [combra-lab/spiking-ddpg-mapless-navigation#1]
I trained a T=5 model according to the tutorial, but the test success rate is only 79.5%, the average path distance is 19.35m, and the average time is 31.5s. Your model has a success rate of 99%, but the average time is 42s. 
Could you help me? 
Thanks!

**Comment by michaelgzt** [comment]
Most probably, you are using a bad model for testing. The best model from training is not necessarily the last saved model. You can select other saved models in the same training session and get a better result.

It's typical for DRL-trained models to have a large variance for their performance in the test environment. This is known for models trained by DDPG. The model we provided as the demo is the best model we got during training. The result we reported in the paper was the average success rate of 5 different models trained by different random seeds. For each training session, we select the best model from all saved models.

**Comment by ding15963** [comment]
Thank you for your prompt reply, I will test some more models.
