### ISSUE TITLE
Hi, Is it possible to implement it with the newer versions of Ubuntu, ROS, and Gazebo?

### ISSUE THREAD

**Issue by h57jafari** [combra-lab/spiking-ddpg-mapless-navigation#2]

**Comment by michaelgzt** [comment]
Hi jafari,

Ubuntu 16.04 and ROS Kinetic are the latest environments for the Turtlebot2 mobile robot and its simulation we used for the experiments. However, if you are using the Turtlebot3, it's possible that you can use Ubuntu 20.04 and ROS2. You can check this link for using Turtlebot3: https://ubuntu.com/blog/simulate-the-turtlebot3. All the training codes for SNN should work without a problem with the new versions of Ubuntu and Pytorch except the part related to ROS.

**Comment by h57jafari** [comment]
thank you.

**Comment by h57jafari** [comment]
Hi, I installed the same version of Ubuntu/ROS/Gazebo as yours. 
with running "roslaunch turtlebot_lidar turtlebot_world.launch", I could see Turtlrbot2 with LiDAR inside the gazebo.
but now when I run it again, I see "segmentation fault (core dumped)" and the 
![image1 (19)](https://user-images.githubusercontent.com/58533979/117874947-9f614c80-b26f-11eb-9106-304401ada24d.JPG)
gazebo does not show anything (all black screen).
what can be the problem, any suggestion? Thank you.
