### ISSUE TITLE
Collision when evaluating

### ISSUE THREAD

**Issue by wolaoer** [combra-lab/spiking-ddpg-mapless-navigation#6]
Hi, @michaelgzt 
I have run your ddpg and sddpg evaluation code in the gazebo simulation environment with your given parameters (I am using ROS noetic and turtlebot3). But I found that the robot always drive in a circle and finally collides with the wall. I got a 0 success rate both on ddpg and sddpg. Should I retrain the model on my simulation environment. Looking forward to your  replay!

**Comment by michaelgzt** [comment]
Hi @wolaoer, thank you for your interest in our work. We suggest retraining the model for new simulation environments and robot setups. As you know, DRL is notoriously bad for generalization.

**Comment by wolaoer** [comment]
@michaelgzt 
Thank you for your advise! By the way,I'd like to know whether the laser data mentioned in your paper is 18 dimention.I wonder why  the input of the simple laser scan constructor is 36.Looking forward to your reply

**Comment by michaelgzt** [comment]
@wolaoer The laser we used supports 360 degrees. In the paper, we only use the forward-facing 180 degrees.
